/*
 * File: app/view/cliente/Lista.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIABS.view.cliente.Lista', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.listaClientes',

    height: 459,
    width: 676,
    layout: {
        type: 'border'
    },
    title: 'Clientes',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    store: 'Clientes',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'nombres',
                            text: 'Nombres'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'paterno',
                            text: 'Paterno'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'materno',
                            text: 'Materno'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'celular',
                            text: 'Celular'
                        }
                    ],
                    viewConfig: {

                    },
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'Clientes'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 50,
                    layout: {
                        type: 'absolute'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 10,
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'button',
                            x: 379,
                            y: 12,
                            text: 'MyButton'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});